---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hetzner-sbox1
provisioner: smb.csi.k8s.io
parameters:
  source: //u354813-sub1.your-storagebox.de/u354813-sub1
  csi.storage.k8s.io/provisioner-secret-name: hetzner-sbox1-creds
  csi.storage.k8s.io/provisioner-secret-namespace: default
  csi.storage.k8s.io/node-stage-secret-name: hetzner-sbox1-creds
  csi.storage.k8s.io/node-stage-secret-namespace: default
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
