#!/usr/bin/env bash

set -euxo pipefail

[ -n "${DISPLAY+x}" ] || exit 0
hash gsettings 2> /dev/null || exit 0

# Disable annoying first-setup messages
gsettings set org.gnome.software first-run false || :

# Setting hot corners
gsettings set org.gnome.shell enable-hot-corners false             || :
gsettings set org.gnome.desktop.interface enable-hot-corners false || :

# Set theme
gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita'     || :
gsettings set org.gnome.desktop.interface cursor-theme 'Adwaita'  || :
gsettings set org.gnome.desktop.interface gtk-key-theme 'Default' || :
gsettings set org.gnome.desktop.interface icon-theme 'Adwaita'    || :
gsettings set org.gnome.desktop.wm.preferences theme 'Adwaita'    || :

# Prefer dark mode
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark' || :

# Other interface settings
gsettings set org.gnome.desktop.interface clock-format '24h'      || :
gsettings set org.gnome.desktop.interface clock-show-seconds true || :
gsettings set org.gnome.desktop.interface clock-show-weekday true || :
gsettings set org.gnome.desktop.interface clock-show-date true    || :
gsettings set org.gnome.desktop.interface enable-animations true  || :

# Desktop settings
gsettings set org.gnome.desktop.background show-desktop-icons false || :
gsettings set org.gnome.desktop.calendar show-weekdate true         || :

# Window management settings
gsettings set org.gnome.mutter center-new-windows true || :

gsettings set org.gnome.mutter auto-maximize true || :
gsettings set org.gnome.mutter edge-tiling true   || :

gsettings set org.gnome.desktop.wm.preferences button-layout 'appmenu:minimize,maximize,close' || :

# Workspaces keybinds

gsettings set org.gnome.shell.keybindings switch-to-application-1 [] || :
gsettings set org.gnome.shell.keybindings switch-to-application-2 [] || :
gsettings set org.gnome.shell.keybindings switch-to-application-3 [] || :
gsettings set org.gnome.shell.keybindings switch-to-application-4 [] || :
gsettings set org.gnome.shell.keybindings switch-to-application-5 [] || :
gsettings set org.gnome.shell.keybindings switch-to-application-6 [] || :
gsettings set org.gnome.shell.keybindings switch-to-application-7 [] || :
gsettings set org.gnome.shell.keybindings switch-to-application-8 [] || :
gsettings set org.gnome.shell.keybindings switch-to-application-9 [] || :

gsettings set org.gnome.desktop.wm.keybindings show-desktop   [] || :
gsettings set org.gnome.shell.keybindings toggle-message-tray [] || :

gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1  "['<Super>1']" || :
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2  "['<Super>2']" || :
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3  "['<Super>3']" || :
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4  "['<Super>4']" || :
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-5  "['<Super>5']" || :
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-6  "['<Super>6']" || :
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-7  "['<Super>7']" || :
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-8  "['<Super>8']" || :
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-9  "['<Super>9']" || :
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-10 "['<Super>0']" || :

gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-1  "['<Super><Shift>1']" || :
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-2  "['<Super><Shift>2']" || :
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-3  "['<Super><Shift>3']" || :
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-4  "['<Super><Shift>4']" || :
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-5  "['<Super><Shift>5']" || :
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-6  "['<Super><Shift>6']" || :
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-7  "['<Super><Shift>7']" || :
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-8  "['<Super><Shift>8']" || :
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-9  "['<Super><Shift>9']" || :
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-10 "['<Super><Shift>0']" || :

gsettings set org.gnome.mutter.keybindings toggle-tiled-left  "['<Super>Left']"  || :
gsettings set org.gnome.mutter.keybindings toggle-tiled-right "['<Super>Right']" || :

gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-1  "['<Primary><Alt>F1']"  || :
gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-2  "['<Primary><Alt>F2']"  || :
gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-3  "['<Primary><Alt>F3']"  || :
gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-4  "['<Primary><Alt>F4']"  || :
gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-5  "['<Primary><Alt>F5']"  || :
gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-6  "['<Primary><Alt>F6']"  || :
gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-7  "['<Primary><Alt>F7']"  || :
gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-8  "['<Primary><Alt>F8']"  || :
gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-9  "['<Primary><Alt>F9']"  || :
gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-10 "['<Primary><Alt>F10']" || :
gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-11 "['<Primary><Alt>F11']" || :
gsettings set org.gnome.mutter.wayland.keybindings switch-to-session-12 "['<Primary><Alt>F12']" || :

gsettings set org.gnome.desktop.wm.keybindings begin-move "['<Super>m']"   || :
gsettings set org.gnome.desktop.wm.keybindings begin-resize "['<Super>r']" || :

gsettings set org.gnome.shell.keybindings toggle-application-view "['<Super><Shift>d']" || :

gsettings set org.gnome.desktop.wm.keybindings switch-applications "['<Alt>Tab']"                 || :
gsettings set org.gnome.desktop.wm.keybindings switch-applications-backward "['<Shift><Alt>Tab']" || :

# Configure default terminal app
gsettings set org.gnome.desktop.default-applications.terminal exec 'kitty' || :
gsettings set org.gnome.desktop.default-applications.terminal exec-arg ''  || :

# Mouse settings
gsettings set org.gnome.desktop.peripherals.mouse natural-scroll false                 || :
gsettings set org.gnome.desktop.peripherals.touchpad natural-scroll true               || :
gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true                 || :
gsettings set org.gnome.desktop.peripherals.touchpad two-finger-scrolling-enabled true || :

# Locate pointer
gsettings set org.gnome.settings-daemon.peripherals.mouse locate-pointer true          || :
gsettings set org.gnome.desktop.interface locate-pointer true                          || :
gsettings set org.gnome.mutter locate-pointer-key 'Control_R'                          || :

# Keyboard settings
gsettings set org.gnome.desktop.input-sources sources "[('xkb','us'),('xkb','pt')]" || :
gsettings set org.gnome.desktop.input-sources per-window true || :

# Haguichi configuration
gsettings set com.github.ztefn.haguichi.config check-internet-hostname 'archlinux.org' || :
gsettings set com.github.ztefn.haguichi.config check-internet-ip '1.1.1.1'             || :
gsettings set com.github.ztefn.haguichi.config nickname "$(uname -n)"                  || :
gsettings set com.github.ztefn.haguichi.config protocol 'both'                         || :
gsettings set com.github.ztefn.haguichi.config reconnect-interval 30                   || :
gsettings set com.github.ztefn.haguichi.config update-interval 15                      || :
gsettings set com.github.ztefn.haguichi.notifications connection-loss true             || :
gsettings set com.github.ztefn.haguichi.notifications member-join true                 || :
gsettings set com.github.ztefn.haguichi.notifications member-leave true                || :
gsettings set com.github.ztefn.haguichi.notifications member-offline true              || :
gsettings set com.github.ztefn.haguichi.notifications member-online true               || :
gsettings set com.github.ztefn.haguichi.ui prefer-dark-theme true                      || :

# Configure PGP keyserver
gsettings set org.gnome.crypto.pgp keyservers "['ldap://keyserver.pgp.com', 'hkps://keys.openpgp.org']" || :

# Maximization settings
gsettings set org.gnome.desktop.wm.preferences action-double-click-titlebar 'toggle-maximize' || :

gsettings set org.gnome.evolution.window maximized true      || :
gsettings set org.gnome.gnome-system-monitor maximized true  || :
gsettings set org.gnome.nautilus.window-state maximized true || :
gsettings set org.gnome.photos window-maximized true         || :
gsettings set org.gnome.Contacts window-maximized true       || :
gsettings set org.gnome.Epiphany.state is-maximized true     || :
gsettings set org.gnome.Maps window-maximized true           || :
gsettings set org.gnome.Music window-maximized true          || :
gsettings set org.gnome.baobab.ui is-maximized true          || :
gsettings set org.gnome.calendar window-maximized true       || :
gsettings set org.gnome.clocks.state.window maximized true   || :

# File picker/manager settings
gsettings set org.gtk.Settings.FileChooser show-hidden true         || :
gsettings set org.gnome.nautilus.preferences show-hidden-files true || :
gsettings set org.gnome.FileRoller.FileSelector show-hidden true    || :
gsettings set org.gtk.gtk4.Settings.FileChooser show-hidden true    || :
