#!/usr/bin/env bash

if [ -z "${TMUX+x}" ]; then
    if [ "$1" == "" ]; then
        exec session
    fi

    echo "Need to be inside a tmux session" >&2
    exit 1
fi

if [ "$1" == "" ]; then
    exec tmux new-window
fi

exec tmux new-window -n "$1"
